In [29]:
import numpy as np 
print(np.random.seed(1))
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,1])
print(arr[-1,-2])
print(arr[:2,:2])
print(arr[:,0])
print(arr[:0,])

None
[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
1
6
[[5 8]
 [0 1]]
[5 0]
[]


In [23]:
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr)
print(arr[3])
print(arr[-2])
print(arr[3:9:2])
print(arr[::-1])

[5 8 9 5 0 0 1 7 6 9]
5
6
[5 0 7]
[9 6 7 1 0 0 5 9 8 5]
