In [21]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(1,50,10)
print(arr)
x=np.sort(arr)
print(x)
print(arr)
y=arr.sort()
print(y)
print(arr)
i=np.argsort(arr)
z=x[i]
print(i)
print(z)

[38 44 13  9 10 12  6 16  1 17]
[ 1  6  9 10 12 13 16 17 38 44]
[38 44 13  9 10 12  6 16  1 17]
None
[ 1  6  9 10 12 13 16 17 38 44]
[0 1 2 3 4 5 6 7 8 9]
[ 1  6  9 10 12 13 16 17 38 44]
