In [4]:
import numpy as np
name=['Alice','Bob','Cathy','Doug']
age=[25,45,37,19]
weight=[55.0,85.5,68.0,61.5]
data=np.zeros(
    4,
    dtype={
        'names':('name','age','weight'),
        'formats':('U10','i4','f8')
    }
)
print("structured array using a compound data type")
print(data.dtype)
data['name']=name
data['age']=age
data['weight']=weight
print("filled stuctured array")
print(data)
print("all names")
print(data['name'])
print("first row of data")
print(data[0])
print("name from the last row")
print(data[data['age']<30]['name'])
np.dtype({
    'names':('name','age','weight'),
    'formats':('U10','i4','f8')
})
np.dtype({
    'names':('name','age','weight'),
    'formats':((np.str_,10),int,np.float32)
})
np.dtype([
    ('name','S10'),
    ('age','i4'),
    ('weight','f8')
])
np.dtype('S10,i4,f8')
tp=np.dtype([
    ('id','i8'),
    ('mat','f8',(3,3))
])
X=np.zeros(1,dtype=tp)
print(X[0])
print(X['mat'][0])


structured array using a compound data type
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
filled stuctured array
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]
all names
['Alice' 'Bob' 'Cathy' 'Doug']
first row of data
('Alice', 25, 55.0)
name from the last row
['Alice' 'Doug']
(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
data_rec=data.view(np.recarray)
print(data_rec.age)

    %timeit data['age']
    %timeit data_rec['age']
    %timeit data_rec.age

IndentationError: unexpected indent (2560969048.py, line 4)